/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes.psi.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import tubes.psi.controller.UserController;
import tubes.psi.model.pojo.User;
import tubes.psi.utilities.DatabaseUtilities;


/**
 *
 * @author A412FL
 */
public class HalamanAdminFrame extends javax.swing.JFrame {


    java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    
    private String tanggal = smpdtfmt.format(tglsekarang);

        public final void setJam(){
    ActionListener taskPerformer = new ActionListener() {
    public void actionPerformed(ActionEvent evt) {
    String nol_jam = "", nol_menit = "",nol_detik = "";
    int jam1 = 0 ;
        int detik1 = 0 ;
        int menit1 = 0 ;
        String waktu = null;
        if(radioBtnBilling1.isSelected()){
            jam1 =  01 ;
            menit1 = 00;
            detik1 = 00;
            waktu = "01:00:00";
        }else if(radioBtnBilling2.isSelected()){
            jam1 =  02 ;
            menit1 = 00;
            detik1 = 00;
            waktu = "02:00:00";
        }else if(radioBtnBilling3.isSelected()){
            jam1 =  03 ;
            menit1 = 00;
            detik1 = 00;
            waktu = "03:00:00";
        }else if(radioBtnBilling4.isSelected()){
            jam1 =  04 ;
            menit1 = 00;
            detik1 = 00;
            waktu = "04:00:00";
        }
        
        

    java.util.Date dateTime = new java.util.Date();
    int nilai_jam = dateTime.getHours();
    int nilai_menit = dateTime.getMinutes();
    int nilai_detik = dateTime.getSeconds();

    if(nilai_jam <= 9) {nol_jam= "0";}
    if(nilai_menit <= 9) {nol_menit= "0";}
    if(nilai_detik <= 9) {nol_detik= "0";}

    String jam = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);
    
    Integer jam2 = Integer.parseInt(jam) + jam1;
    Integer menit2 = Integer.parseInt(menit) + menit1;
    Integer detik2 = Integer.parseInt(detik) + detik1;
    
    
    lblwaktu.setText(jam+":"+menit+":"+detik+"");
    txtWaktuHabis.setText(jam2+":"+menit2+":"+detik2+"");
    }
    };
new Timer(1000, taskPerformer).start();
}
    private DefaultTableModel model;
    UserController con = new UserController();
    public HalamanAdminFrame() throws SQLException {
        initComponents();
        setTitle("Kelola Admin");
        populateDataToTable();
        lbltgl.setText(tanggal);
        setJam();
        txtWaktuHabis.setEnabled(false);
        txtHarga.setEnabled(false);
    }
    
    public void populateDataToTable() throws SQLException {
        model = (DefaultTableModel) tblUser.getModel();
          List<User> user = con.loadUser();

        for (User us : user) {
            Object[] row = new Object[8];
            row[0] = us.getId();
            row[1] = us.getNama();
            row[2] = us.getBilling();
            row[3] = us.getPc();
            row[4] = us.getTanggal();
            row[5] = us.getJam_mulai();
            row[6] = us.getJam_berhenti();
            row[7] = us.getHarga();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        btnGroupBilling = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblBilling = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbltgl = new javax.swing.JLabel();
        lblwaktu = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        radioBtnBilling1 = new javax.swing.JRadioButton();
        radioBtnBilling2 = new javax.swing.JRadioButton();
        radioBtnBilling3 = new javax.swing.JRadioButton();
        radioBtnBilling4 = new javax.swing.JRadioButton();
        lblPc = new javax.swing.JLabel();
        komputer = new javax.swing.JComboBox<>();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txtWaktuHabis = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Password", "Billing", "PC", "Tanggal", "Jam Mulai", "Jam Selesai", "Harga"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        btnTambah.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\PSI\\Praktikum\\TA_parkir\\src\\icon\\30-512.png")); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        lblNama.setText("Nama :");

        lblBilling.setText("Billing  :");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\PSI\\Praktikum\\TA_parkir\\src\\icon\\hapus.png")); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\PSI\\Praktikum\\warnet\\src\\warnet\\icons8_Computer_100px_1.png")); // NOI18N

        lbltgl.setText("jLabel2");

        lblwaktu.setText("jLabel2");

        lblId.setText("ID      :");
        lblId.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblIdAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnGroupBilling.add(radioBtnBilling1);
        radioBtnBilling1.setText("1 Jam");
        radioBtnBilling1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnBilling1ActionPerformed(evt);
            }
        });

        btnGroupBilling.add(radioBtnBilling2);
        radioBtnBilling2.setText("2 Jam");
        radioBtnBilling2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnBilling2ActionPerformed(evt);
            }
        });

        btnGroupBilling.add(radioBtnBilling3);
        radioBtnBilling3.setText("3 Jam");
        radioBtnBilling3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnBilling3ActionPerformed(evt);
            }
        });

        btnGroupBilling.add(radioBtnBilling4);
        radioBtnBilling4.setText("4 Jam");
        radioBtnBilling4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnBilling4ActionPerformed(evt);
            }
        });

        lblPc.setText("Pilih PC :");

        komputer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected PC", "PC 1", "PC 2", "PC 3", "PC 4", "PC 5", "PC 6", "PC 7", "PC 8" }));
        komputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komputerActionPerformed(evt);
            }
        });

        lblHarga.setText("Harga : ");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        lbl2.setText("Waktu Habis :");

        txtWaktuHabis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaktuHabisActionPerformed(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\PSI\\Praktikum\\TA_parkir\\src\\icon\\Money Transfer-64.png")); // NOI18N
        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnKeluar.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\PSI\\Praktikum\\TA_parkir\\src\\icon\\Exit-64.png")); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("Halaman Kelola Member Warnet");
        jLabel2.setIconTextGap(6);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("ARIFAL NET");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblBilling)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBtnBilling1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnBilling2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBtnBilling4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnBilling3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblId)
                            .addComponent(lblPc)
                            .addComponent(lblNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(komputer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbltgl)
                            .addComponent(lblwaktu))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtWaktuHabis, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl2)
                                    .addComponent(lblHarga))
                                .addGap(30, 30, 30)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(225, 225, 225))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnReport)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2)
                            .addComponent(txtWaktuHabis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioBtnBilling4)
                            .addComponent(radioBtnBilling3)
                            .addComponent(lblBilling)
                            .addComponent(lblwaktu))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioBtnBilling1)
                                    .addComponent(radioBtnBilling2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPc)
                                    .addComponent(komputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbltgl)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnReport)
                                .addComponent(btnKeluar))))
                    .addComponent(btnHapus))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        int status = 0;
        int detik1 = 0 ;
        int menit1 = 0 ;
        String waktu = null;
        if(radioBtnBilling1.isSelected()){
            waktu = "1 jam";
        }else if(radioBtnBilling2.isSelected()){
            waktu = "2 jam";
        }else if(radioBtnBilling3.isSelected()){
            waktu = "3 jam";
        }else if(radioBtnBilling4.isSelected()){
            waktu = "4 jam";

        }
        try {
            DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
            
            status = con.insert(new User(txtId.getText(), txtNama.getText(), waktu.toString() ,komputer.getSelectedItem().toString(), txtHarga.getText(),
                     lbltgl.getText(), lblwaktu.getText(), txtWaktuHabis.getText()));
            refreshTable();
        } catch (SQLException ex){
            Logger.getLogger(HalamanAdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (status == 1) {
            JOptionPane.showMessageDialog(this,"Member Baru Berhasil Di tambahkan");
        } else {
            JOptionPane.showMessageDialog(this,"Member Baru Gagal Di tambahkan");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int status = 0;
        try {
            DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
            status = con.hapus(new User(txtId.getText()));
            refreshTable();
        } catch (SQLException ex){
            Logger.getLogger(HalamanAdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Member baru Berhasil Di hapus");
        } else {
            JOptionPane.showMessageDialog(this, "Member baru Gagal Di hapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        int selectedIndex = tblUser.getSelectedRow();
        txtId.setText(model.getValueAt(selectedIndex, 0).toString());
        
    }//GEN-LAST:event_tblUserMouseClicked

    private void lblIdAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblIdAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIdAncestorAdded

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void radioBtnBilling1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnBilling1ActionPerformed
        // TODO add your handling code here:
                if (this.radioBtnBilling1.isSelected()){
            this.txtHarga.setText("5000");
        }
    }//GEN-LAST:event_radioBtnBilling1ActionPerformed

    private void radioBtnBilling2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnBilling2ActionPerformed
        // TODO add your handling code here:
             if (this.radioBtnBilling2.isSelected()){
            this.txtHarga.setText("10000");
        }
    }//GEN-LAST:event_radioBtnBilling2ActionPerformed

    private void radioBtnBilling3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnBilling3ActionPerformed
             if (this.radioBtnBilling3.isSelected()){
            this.txtHarga.setText("15000");
        }
    }//GEN-LAST:event_radioBtnBilling3ActionPerformed

    private void radioBtnBilling4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnBilling4ActionPerformed
        if (this.radioBtnBilling4.isSelected()){
            this.txtHarga.setText("20000");
        }

    }//GEN-LAST:event_radioBtnBilling4ActionPerformed

    private void komputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komputerActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtWaktuHabisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktuHabisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktuHabisActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport("src/tubes/psi/report/biilling_report.jasper", null, DatabaseUtilities.getConnection());
            JasperViewer.viewReport(jasperPrint, true);
        }catch (JRException e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
                Object[] options = {"Ya", "Tidak, tetap di halaman"};
        int dialog = JOptionPane.showOptionDialog(this, "Apakah Anda yakin akan Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (dialog == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void refreshTable() throws SQLException {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);
        populateDataToTable();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HalamanAdminFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(HalamanAdminFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupBilling;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> komputer;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblBilling;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPc;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JLabel lblwaktu;
    private javax.swing.JRadioButton radioBtnBilling1;
    private javax.swing.JRadioButton radioBtnBilling2;
    private javax.swing.JRadioButton radioBtnBilling3;
    private javax.swing.JRadioButton radioBtnBilling4;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtWaktuHabis;
    // End of variables declaration//GEN-END:variables

    
}
